// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkxG44yoQCn1no9xBRkLtJ8PpCvtlb0MY',
    appId: '1:584029897174:android:ec8a8abc63a69807652477',
    messagingSenderId: '584029897174',
    projectId: 'espambiente-db67e',
    databaseURL: 'https://espambiente-db67e-default-rtdb.firebaseio.com',
    storageBucket: 'espambiente-db67e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaIvhfdbqQvGIxyDbe5MmqYqNcLbKl9cs',
    appId: '1:584029897174:ios:1389d2bc61ad06e7652477',
    messagingSenderId: '584029897174',
    projectId: 'espambiente-db67e',
    databaseURL: 'https://espambiente-db67e-default-rtdb.firebaseio.com',
    storageBucket: 'espambiente-db67e.firebasestorage.app',
    iosBundleId: 'unis.jhonatantana.monitorAmbiente',
  );
}
